input-ipc-server=/tmp/mpvsocket
hr-seek-framedrop=no
save-position-on-quit
resume-playback
ignore-path-in-watch-later-config
border=no				# recommended for ModernX OSC
fullscreen
screenshot-directory=/tmp/
ontop=no
fs=no
# hwdec=auto
audio-spdif=ac3,eac3,dts-hd,truehd
volume-max=150
volume=60
keepaspect=no
sub-auto=fuzzy
sub-font="JetBrains Mono Nerd Font"
sub-bold=yes
sub-font-size=30
sub-visibility=no
# alang=hi,en
# slang=hi,en
# vlang=hi,en
alang=en,hi
slang=en,hi
vlang=en,hi
track-auto-selection=yes
