exec-once=systemctl --user start plasma-polkit-agent
exec-once = mako
exec-once = blueman-applet
# exec-once = nm-applet &
exec-once = wl-paste --watch cliphist store
exec-once = swww init
exec-once = sleep 1 && /home/iCode/.config/hypr/scripts/alarm.sh

# exec-once = [workspace 1 silent] $terminal --title TMUX -o background_opacity=0.0 bash -c "tmux attach"
exec-once = [workspace 1 silent] $terminal --title TMUX -o background_opacity=0.0 bash -c "zellij attach Boot"
exec-once = [workspace 2 silent] $browser
exec-once = [workspace 3 silent] ${super-terminal}
exec-once = [workspace 4 silent] ${fast-terminal}

exec-once = /home/iCode/.config/hypr/scripts/logintime.sh
exec-once = sleep 3 && /home/iCode/.config/hypr/scripts/multitask.sh start
