exec-once = systemctl --user start plasma-polkit-agent
exec-once = mako
exec-once = blueman-applet
exec-once = kdeconnect-indicator
exec-once = nm-applet
exec-once = hyprpaper
exec-once = wl-paste --watch cliphist store
exec-once = swww-daemon

exec-once = /home/iCode/.config/hypr/scripts/alarm.sh 1
exec-once = /home/iCode/.config/hypr/scripts/battery.sh
exec-once = /home/iCode/.config/hypr/scripts/logintime.sh

# exec-once = [workspace 1 silent] $terminal --title TMUX -o background_opacity=0.0 bash -c "tmux attach"
exec-once = [workspace 1 silent] $terminal --title TMUX -o background_opacity=0.0 bash -c "zellij attach Boot"
exec-once = [workspace 2 silent] $browser
exec-once = [workspace 3 silent] ${fast-terminal}
