# Laptop multimedia keys for volume and LCD brightness
# bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%+
# bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%-
# bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
# bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
# bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
# bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-

bindel = ,F1, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,F2, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%-
bindel = ,F3, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%+
bindel = ,F4, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,F11, exec, ~/.config/hypr/scripts/brightness.sh --dec
bindel = ,F12, exec, ~/.config/hypr/scripts/brightness.sh --inc
bindel = SHIFT ,F11, exec, ~/.config/hypr/scripts/brightness.sh --min
bindel = SHIFT ,F12, exec, ~/.config/hypr/scripts/brightness.sh --max
