monitor=,preferred,auto,auto

$terminal = kitty
${fast-terminal} = foot
${super-terminal} = waveterm
$multiplexerMod = CTRL SHIFT
$browser = qutebrowser
$fileManager = dolphin
$menu = tofi-drun

$mainMod = SUPER # Sets "Windows" key as main modifier
$multiMod = ALT

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

general { 
    gaps_in = 2
    gaps_out = 5
    border_size = 1
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    resize_on_border = true 
    hover_icon_on_border = true
    allow_tearing = false
    layout = master
}

binds {
  workspace_back_and_forth=true
  allow_workspace_cycles=true
  pass_mouse_when_bound=false
}

animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

master {
    allow_small_split = false
    new_status = master
    new_on_top = true
    orientation = top
    always_center_master = true
}

misc { 
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    close_special_on_empty = true
    font_family = JetBrains Mono Nerd Font
    animate_manual_resizes = true
    animate_mouse_windowdragging = false
    focus_on_activate = true
}

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = ctrl:nocaps, shift:both_capslock
    kb_rules =

    follow_mouse = true
    repeat_delay = 600
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    focus_on_close = 0
    touchpad {
        disable_while_typing = true
        middle_button_emulation = true
        tap-to-click = true
        drag_lock = true
        tap-and-drag = true
        natural_scroll = false
    }
}

gestures {
  workspace_swipe=1
  workspace_swipe_fingers=3
  workspace_swipe_distance=400
  workspace_swipe_invert=1
  workspace_swipe_min_speed_to_force=20
  workspace_swipe_cancel_ratio=0.45
  workspace_swipe_create_new=0
  workspace_swipe_forever=1
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

source = ~/.config/hypr/auto-start.conf
source = ~/.config/hypr/run-time/multitask
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/fn_keybinds.conf
source = ~/.config/hypr/workspace_keybinds.conf
source = ~/.config/hypr/keybinds.conf
