bind = $mainMod, RETURN, exec, ${fast-terminal}
bind = $mainMod, BACKSPACE, exec, $terminal --title TMUX -o background_opacity=0.0 bash -c "zellij attach Boot"
# bind = $mainMod SHIFT, BACKSPACE, exec, $terminal --title TMUX -o background_opacity=0.0 bash -c "tmux new"

bind = $mainMod, Q, killactive,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, UP, togglefloating,
bind = $mainMod, UP, centerwindow,
bind = $mainMod, Down, layoutmsg, swapwithmaster master
bind = $mainMod SHIFT, Down, layoutmsg, orientationcycle left top center
bind = $mainMod, SPACE, exec, $menu | xargs hyprctl dispatch exec --
bind = $mainMod, F, fullscreen
bind = $mainMod, Escape, exec, /home/iCode/.config/hypr/scripts/unistart.sh wlogout
bind = $mainMod, X, exec, /home/iCode/.config/hypr/scripts/unistart.sh waybar
bind = $mainMod, V, exec, cliphist list | tofi | cliphist decode | wl-copy # open clipboard manager

bind = $multiMod, R, exec, /home/iCode/.config/hypr/scripts/alarm.sh
bind = $multiMod, M, exec, $terminal --title MULTITASK bash -c "/home/iCode/media/music.sh"
bind = $multiMod SHIFT, M, exec, $terminal --title MOVIE bash -c "/home/iCode/media/movie.sh"
bind = $multiMod, Q, exec, /home/iCode/.config/hypr/scripts/multitask.sh stop
bind = $multiMod, Z, exec, /home/iCode/.config/hypr/scripts/multitask.sh pause
bind = $multiMod, H, exec, /home/iCode/.config/hypr/scripts/multitask.sh step-backward
bind = $multiMod SHIFT, H, exec, /home/iCode/.config/hypr/scripts/multitask.sh jump-backward
bind = $multiMod, L, exec, /home/iCode/.config/hypr/scripts/multitask.sh step-forward
bind = $multiMod SHIFT, L, exec, /home/iCode/.config/hypr/scripts/multitask.sh jump-forward

# bind = $mainMod, P, pseudo, # dwindle
# bind = $mainMod, J, togglesplit, # dwindle
# bind = $mainMod, M, exit,
