bind = $mainMod, RETURN, exec, ${fast-terminal}
bind = $mainMod SHIFT, RETURN, exec, $terminal
bind = $mainMod, BACKSPACE, exec, ${fast-terminal} --title ZELLIJ bash -c "zellij attach Boot"
bind = $mainMod SHIFT, BACKSPACE, exec, $terminal --title TMUX -o background_opacity=0.0 bash -c "zellij attach Boot"
# bind = $mainMod SHIFT, BACKSPACE, exec, $terminal --title TMUX -o background_opacity=0.0 bash -c "tmux new"

bind = , PRINT, exec, /home/iCode/.config/hypr/scripts/screenshot.sh sf
bind = SHIFT, PRINT, exec, /home/iCode/.config/hypr/scripts/screenshot.sh rc
bind = $mainMod, PRINT, exec, /home/iCode/.config/hypr/scripts/screenshot.sh ri

bind = $mainMod, Q, killactive,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, B, exec, /home/iCode/.config/hypr/scripts/battery.sh notify
bind = $mainMod SHIFT, B, exec, /home/iCode/.config/hypr/scripts/battery.sh custom

bind = $mainMod, SPACE, exec, $menu | xargs hyprctl dispatch exec --
bind = $mainMod, F, fullscreen
bind = $mainMod, Escape, exec, /home/iCode/.config/hypr/scripts/unistart.sh wlogout -b 2
bind = $mainMod, X, exec, /home/iCode/.config/hypr/scripts/unistart.sh waybar
bind = $mainMod, V, exec, cliphist list | tofi | cliphist decode | wl-copy # open clipboard manager
bind = $mainMod, F5, exec, /home/iCode/.config/hypr/scripts/multitask.sh toggle
bind = $mainMod, R, exec, zellij --session Boot run --floating --close-on-exit -- /home/iCode/.config/hypr/scripts/motivate.sh
bind = $mainMod, C, exec, zellij --session Boot run --floating --close-on-exit -- /home/iCode/.config/hypr/scripts/cheatsheet.sh

bind = $multiMod, R, exec, /home/iCode/.config/hypr/scripts/alarm.sh
# bind = $multiMod, M, exec, ${fast-terminal} --title MULTITASK bash -c "/home/iCode/media/music.sh"
# bind = $multiMod SHIFT, M, exec, ${fast-terminal} --title MOVIE bash -c "/home/iCode/media/movie.sh"
# bind = $multiMod, V, exec, ${fast-terminal} --title VIDEOS bash -c "/home/iCode/media/videos.sh"
bind = $multiMod, M, exec, zellij --session Boot run --floating --close-on-exit -- /home/iCode/media/music.sh
bind = $multiMod SHIFT, M, exec, zellij --session Boot run --floating --close-on-exit -- /home/iCode/media/movie.sh
bind = $multiMod, V, exec, zellij --session Boot run --floating --close-on-exit -- /home/iCode/media/videos.sh
bind = $multiMod, Q, exec, /home/iCode/.config/hypr/scripts/multitask.sh stop
bind = $multiMod, Z, exec, /home/iCode/.config/hypr/scripts/multitask.sh pause
bind = $multiMod, F5, exec, /home/iCode/.config/hypr/scripts/multitask.sh restart
bind = $multiMod, H, exec, /home/iCode/.config/hypr/scripts/multitask.sh step-rewind
bind = $multiMod SHIFT, H, exec, /home/iCode/.config/hypr/scripts/multitask.sh fast-rewind
bind = $multiMod, L, exec, /home/iCode/.config/hypr/scripts/multitask.sh step-forward
bind = $multiMod SHIFT, L, exec, /home/iCode/.config/hypr/scripts/multitask.sh fast-forward
bind = $multiMod, N, exec, /home/iCode/.config/hypr/scripts/multitask.sh next
bind = $multiMod, P, exec, /home/iCode/.config/hypr/scripts/multitask.sh previous

bind = $multiMod, S, exec, /home/iCode/.config/hypr/scripts/multitask.sh subtitle-on
bind = $multiMod SHIFT, S, exec, /home/iCode/.config/hypr/scripts/multitask.sh subtitle-off

bind = $multiMod, XF86AudioLowerVolume, exec, /home/iCode/.config/hypr/scripts/multitask.sh dec-vol
bind = $multiMod SHIFT, XF86AudioLowerVolume, exec, /home/iCode/.config/hypr/scripts/multitask.sh min-vol
bind = $multiMod, XF86AudioRaiseVolume, exec, /home/iCode/.config/hypr/scripts/multitask.sh inc-vol
bind = $multiMod SHIFT, XF86AudioRaiseVolume, exec, /home/iCode/.config/hypr/scripts/multitask.sh max-vol

# bind = $mainMod, P, pseudo, # dwindle
# bind = $mainMod, J, togglesplit, # dwindle
# bind = $mainMod, M, exit,
