windowrule = workspace 1, mpv
windowrule = float, mpv
windowrule = nofocus, mpv
windowrule = size 100% 100%, mpv
windowrule = noinitialfocus, mpv
windowrule = noborder, mpv

windowrule = workspace 1, title:^(TMUX)$
windowrule = float, title:^(TMUX)$
windowrule = center, title:^(TMUX)$
windowrule = size 100% 100%, title:^(TMUX)$
windowrule = stayfocused, title:^(TMUX)$

windowrule = workspace 2, qutebrowser
windowrule = float, qutebrowser
windowrule = center, qutebrowser
windowrule = size 100% 100%, qutebrowser
windowrule = noborder, qutebrowser
windowrule = noshadow, qutebrowser

windowrule = workspace 7, title:^(UPDATE-SYS)$
windowrule = float, title:^(UPDATE-SYS)$
windowrule = fullscreen, title:^(UPDATE-SYS)$
windowrule = noborder, title:^(UPDATE-SYS)$
windowrule = noshadow, title:^(UPDATE-SYS)$

windowrule = workspace 9, title:^(MULTITASK)$
windowrule = float, title:^(MULTITASK)$
windowrule = center, title:^(MULTITASK)$
windowrule = size 100% 100%, title:^(MULTITASK)$

windowrule = workspace 10, title:^(MOVIE)$
windowrule = float, title:^(MOVIE)$
windowrule = center, title:^(MOVIE)$
windowrule = size 100% 100%, title:^(MOVIE)$

workspace = 1, rounding:false, bordersize:0, shadow:false, animation: false
workspace = 2, bordersize:0, shadow:false,

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
